# Первый этап: сборка приложения
FROM golang:latest AS builder

# Устанавливаем переменную окружения GO111MODULE в значение "on"
ENV GO111MODULE=on

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем go.mod и go.sum для загрузки зависимостей
COPY go.mod .
COPY go.sum .

# Загружаем зависимости
RUN go mod download

# Копируем содержимое папки internal
COPY internal/agent internal/agent

# Копируем папку config
COPY config/ config/

# Копируем исполняемый файл агента внутрь папки cmd
COPY cmd/agentmain /app/cmd/agentmain

# Устанавливаем права на выполнение для исполняемого файла
RUN chmod +x /app/cmd/agentmain

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/cmd/agentmain /app/cmd/agentmain

# Второй этап: создание минимального образа
FROM scratch

# Копируем исполняемый файл из предыдущего этапа
COPY --from=builder /app/cmd/agentmain /app/cmd/agentmain

# Указываем исполняемый файл в качестве команды по умолчанию
CMD ["/app/cmd/agentmain"]